# Project information
site_name: Playbooks AI
site_url: https://github.com/playbooks-ai/playbooks
site_description: >-
  Build AI Agents with Natural Language Programming

# Repository
repo_name: playbooks
repo_url: https://github.com/playbooks-ai/playbooks

# Copyright
copyright: Copyright Playbooks AI 2025

# Custom CSS
extra_css:
  - assets/stylesheets/custom.css

# Configuration
theme:
  name: material
  font:
    text: Google Sans
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/play
  palette:
    - scheme: default
      primary: slate
      accent: slate
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.top
    - navigation.tracking
    - toc.follow

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __codeline__
      pygments_lang_class: true
      pygments_style: vs
      noclasses: false
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["../playbooks/src"]
          options:
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true
            merge_init_into_class: true
            docstring_style: google
            members_order: source
            show_signature_annotations: true
            preload_modules:
              - playbooks.agents

# Navigation
nav:
  - Home: index.md
  - Getting Started: getting-started/index.md
  - Tutorial: tutorials/index.md
  - Reference:
    - Configuration System: reference/config.md
    - Supported Models: reference/models.md
    - Playbooks AI: reference/playbooks-ai.md
    - Playbooks Language: reference/playbooks-language.md
    - Playbooks Assembly Language: reference/playbooks-assembly-language.md
    - Agents: reference/agents.md
    - MCP based Agents: reference/mcp-agent.md
    - Exported and Public Playbooks: reference/exported-and-public-playbooks.md
    - Playbook Types: reference/playbook-types.md
    - Built-in Playbooks: reference/builtin-playbooks.md
    - Triggers: reference/triggers.md
    - Context Engineering: reference/context-engineering.md
    - Description Placeholders: reference/description-placeholders.md
