# Project information
site_name: Playbooks AI
site_url: https://github.com/playbooks-ai/playbooks
site_description: >-
  Build AI Agents with Natural Language Programming

# Repository
repo_name: playbooks
repo_url: https://github.com/playbooks-ai/playbooks

# Copyright
copyright: Copyright Playbooks AI 2025

# Custom CSS
extra_css:
  - stylesheets/custom.css

# Configuration
theme:
  name: material
  font:
    text: Google Sans
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/play
  palette:
    - scheme: default
      primary: slate
      accent: slate
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.top
    - navigation.tracking
    - toc.follow

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["../playbooks/src"]
          options:
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true
            merge_init_into_class: true
            docstring_style: google
            members_order: source
            show_signature_annotations: true
            preload_modules:
              - playbooks.agents

# Navigation
nav:
  - Home: index.md
  - Get Started:
    - get-started/index.md
    - Installation: get-started/installation.md
    - Quickstart: get-started/quickstart.md
  - Guides:
    - guides/index.md
    - Adding Triggers: guides/adding-triggers.md
    - User Interaction: guides/user-interaction.md
    - Call Playbooks: guides/calling-playbooks.md
    - Variables & Expressions: guides/variables-and-expressions.md
    - Run with CLI: guides/run-with-cli.md
    - Environment Variables: guides/environment-variables.md
    - Compilation and Cache: guides/compilation-and-cache.md
  - Integrations:
    - integrations/vscode.md
    - integrations/langfuse.md
  - Tutorials:
    - tutorials/index.md
    - Part 0 – Install and first run: tutorials/part-0-install-first-run.md
    - Part 1 – User interaction: tutorials/part-1-user-interaction.md
    - Part 2 – Triggers: tutorials/part-2-triggers.md
    - Part 3 – Calls (Markdown ↔ Python): tutorials/part-3-calls-markdown-python.md
    - Part 4 – Agent‑to‑Agent calls: tutorials/part-4-agent-to-agent.md
    - Part 5 – Meetings: tutorials/part-5-meetings.md
    - Part 6 – Observability and debugging: tutorials/part-6-observability-debugging.md
    - Part 7 – Web Server and Playground: tutorials/part-7-web-server-playground.md
  - Playbooks Language:
    - playbooks-language/index.md
    - Playbooks Language: playbooks-language/playbooks-language.md
    - Playbooks Assembly Language: playbooks-language/playbooks-assembly-language.md
    - Metadata: playbooks-language/metadata.md
    - Playbooks as the CLS and CLR: playbooks-language/cls.md
  - Playbook Types:
    - playbook-types/index.md
    - Markdown Playbooks: playbook-types/markdown-playbooks.md
    - ReAct Playbooks: playbook-types/react-playbooks.md
    - Raw Prompt Playbooks: playbook-types/raw-prompt-playbooks.md
    - Python Playbooks: playbook-types/python-playbooks.md
    - External Playbooks: playbook-types/external-playbooks.md
    - Built-in Playbooks: playbook-types/builtin-playbooks.md
  - Triggers:
    - triggers/index.md
  - Artifacts:
    - artifacts/index.md
  - Agents:
    - agents/index.md
    - MCP Agents: agents/mcp-agent.md
    - Exported and Public Playbooks: agents/exported-and-public-playbooks.md
  - Runtime:
    - runtime/index.md
    - Common Language Runtime (CLR): runtime/clr.md
  - Applications:
    - applications/index.md
    - applications/cli.md
    - applications/web-server.md
    - applications/playground.md
  - Observability:
    - observability/index.md
  - FAQs: faqs.md
  - Glossary: glossary.md
  - Advanced Concepts:
    - advanced/index.md
    - Playbooks Protocol: advanced/playbooks-protocol.md
    - Observer Agents: advanced/observer-agents.md
    - Dynamic Playbook Generation: advanced/dynamic-playbook-generation.md
    - Dynamic Playbook Rewriting: advanced/dynamic-playbook-rewriting.md
  # - API Reference:
  #   - api-reference/index.md